# Generated by Django 4.1.5 on 2023-01-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='title',
            new_name='treatment',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.note'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='core.prescription'),
        ),
    ]
