# Generated by Django 4.1.5 on 2023-02-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_clienthealthstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienthealthstatus',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_status', to='core.client'),
        ),
    ]
